# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc4e1d4ff50670655e0b9d955cce7efb2be195b6eef370f4bf7c1b771bb9193e30665686a5f61f884b541faebb62f92be60a8eb23c1bc0a9baf5becd25932d0

test:
  secret_key_base: 70fb03754fe70df6da746eeb21aa6a80fca93024cf796ba7672fd665773f828b1caf05123b10c03c8dcaaae0eaefa8d9596d0ce402504c0f23743974db7a8510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
